name: Remix Pipelines

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  common-setup:
    name: Common Pipeline Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Common Setup
        uses: ./.github/actions/common
        with:
          node-version: '22'
          cache: 'yarn'

  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    needs: common-setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Common Setup
        uses: ./.github/actions/common
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Run Linter
        run: yarn run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: common-setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Common Setup
        uses: ./.github/actions/common
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Run Tests
        run: yarn run test

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: common-setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Common Setup
        uses: ./.github/actions/common
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Build Project
        run: yarn run build

  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    needs: common-setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Common Setup
        uses: ./.github/actions/common
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Check Formatting
        run: yarn run format:check

  deploy:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Common Setup
        uses: ./.github/actions/common
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t sachadvr/remix-app .

      - name: Push Docker Image
        run: docker push sachadvr/remix-app
